apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity
  template:    
    metadata:
      labels:
        app: activity
    spec:
      containers:
      - name: activity
        image: registry.cn-hangzhou.aliyuncs.com/kube/activity:2026-05-10-d69c7c0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"     
            memory: "16Mi"  
          limits:
            cpu: "500m"     
            memory: "512Mi" 
        ports:
        - containerPort: 50051
        env: 
        - name: TOKEN
          value: "vUZvdEy9+"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
      - name: aliyun-registry-secret
---
# 自动创建的 Service
apiVersion: v1
kind: Service
metadata:
  name: activity
spec:
  selector:
    app: activity
  ports:
  - port: 50054
    targetPort: 50054
  type: ClusterIP